Repository kanha638/Price-Tracker, pull requests merged in 2023-05, with the labels that each got.

#47 notification service startup completed
  servers/notification/.gitignore
  servers/notification/Dockerfile
  servers/notification/docker-compose.yml
  servers/notification/package-lock.json
  servers/notification/package.json
  servers/notification/src/app-config.ts
  servers/notification/src/index.ts
  servers/notification/tsconfig.json
Labels: enhancement

#48 Added Myntra support. Product Category is also tracked now.
  servers/scrapping-server/app/product/scrapers.py
Labels: enhancement

#51 Forgot pass inside public server implemented.
  servers/public-server/src/controllers/auth.controller.ts
  servers/public-server/src/middleware/rateLimiters.ts
  servers/public-server/src/routes/auth.ts
  testing/p-server/Auth.postman_collection.json
Labels: enhancement

#52 sign-in and sign-up is integrated with backend
  client/src/components/header/Navbar.jsx
  client/src/pages/Signin.js
  client/src/pages/Signup.js
Labels: enhancement

#54 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#58 apply condition to password length
  servers/public-server/src/controllers/auth.controller.ts
Labels: bug

#60 Product add integration into new UI of the application.
  client/src/components/LandingPage/LandingPage.jsx
  client/src/components/headSlider/HeadSlider.jsx
  client/src/components/headSlider/HeadSliderCard.jsx
  client/src/components/headSlider/HeaderBox.jsx
  client/src/middleware/auth.js
  client/src/slices/userSlice.js
Labels: enhancement

#64 sliding issue in headerbox is resolved
  client/src/components/headSlider/HeadSliderCard.jsx
Labels: bug

#66 Error handling scraping server
  servers/scrapping-server/.gitignore
  servers/scrapping-server/app/product/routes.py
  servers/scrapping-server/app/product/scrapers.py
  servers/scrapping-server/app/product/trackers.py
  servers/scrapping-server/run.py
Labels: enhancement

#68 profile page ui completed
  client/src/assets/images/profileimg.avif
  client/src/components/header/Search.jsx
Labels: enhancement, UI/UX

#69 Profile Picture update functionality completed.
  client/src/components/header/Profile.jsx
  client/src/components/header/Search.jsx
Labels: enhancement

#72 startup for folder creation + integration scraping server error + prev profile img deletion on new upload.
  servers/public-server/.gitignore
  servers/public-server/src/controllers/files.controller.ts
  servers/public-server/src/controllers/product.controller.ts
  servers/public-server/src/controllers/user.controller.ts
  servers/public-server/src/index.ts
  servers/public-server/src/startup.ts
Labels: enhancement, public-server

#75 fixed error handling bugs in scrapping server
  servers/scrapping-server/app/product/routes.py
  servers/scrapping-server/app/product/scrapers.py
Labels: bug

#77 formhandling in profile update component
  client/src/components/header/Profile.jsx
Labels: enhancement

#79 mui avatar component for user profile img
  client/src/components/header/Profile.jsx
  client/src/components/header/Search.jsx
Labels: enhancement

#80 included website name in response
  servers/public-server/src/controllers/product.controller.ts
  servers/scrapping-server/app/product/routes.py
  servers/scrapping-server/app/product/scrapers.py
Labels: urgent, public-server, scraping-server

#84 configured ci for scraping server unit tests
  .github/workflows/run_tests.yml
Labels: enhancement

#81 Category Dropdown enhancement and my-product page tablet-and mobile v…
  client/src/components/header/Navbar.jsx
  client/src/components/shops/Shop.jsx
  client/src/styles/style.css
Labels: enhancement, UI/UX

#82 Added tests to test functionality of scrapping server
  servers/scrapping-server/app/product/scrapers.py
  servers/scrapping-server/requirements.txt
  servers/scrapping-server/tests/__init__.py
  servers/scrapping-server/tests/bad_urls.txt
  servers/scrapping-server/tests/good_urls.txt
  servers/scrapping-server/tests/test_add_product.py
  servers/scrapping-server/tests/test_scrapers.py
Labels: enhancement, dependencies, python, scraping-server
