Repository kanha638/Price-Tracker, pull requests merged in 2023-06, with the labels that each got.

#96 Reset password error resolve
  client/src/App.jsx
  client/src/pages/SetPasswordPage.jsx
  client/src/slices/userSlice.js
  servers/notification/src/templates/user.ts
  servers/public-server/src/controllers/auth.controller.ts
Labels: bug

#100 Google auth login integration completed both on frontend and backend.
  client/package-lock.json
  client/package.json
  client/src/components/headSlider/HeaderBox.jsx
  client/src/components/headSlider/SigninBox.jsx
  client/src/components/header/Profile.jsx
  client/src/environment/config.js
  client/src/middleware/auth.js
  client/src/pages/Signin.jsx
  client/src/pages/Signup.jsx
  client/src/utils/utilities.js
  servers/public-server/package-lock.json
  servers/public-server/package.json
  servers/public-server/src/controllers/auth.controller.ts
  servers/public-server/src/routes/auth.ts
  testing/p-server/Auth.postman_collection.json
Labels: enhancement

#101 My and subscribed data flow
  client/package-lock.json
  client/package.json
  client/src/components/myproducts/MyProducts.jsx
  client/src/components/shops/Shop.jsx
  client/src/components/shops/ShopBox.jsx
  client/src/components/shops/ShopCart.jsx
  client/src/components/shops/style.css
  client/src/components/subscribedProducts/SubscribedProducts.jsx
  client/src/middleware/product.js
  client/src/slices/userSlice.js
  servers/public-server/src/controllers/product.controller.ts
Labels: enhancement, new feature

#103 Added dynamic stars and product's website icon/img.
  client/src/components/shops/ShopBox.jsx
  servers/public-server/src/controllers/product.controller.ts
Labels: enhancement

#102 Added Ajio Scraper
  servers/scrapping-server/app/product/globals.py
  servers/scrapping-server/app/product/scrapers.py
  servers/scrapping-server/app/product/utils.py
  servers/scrapping-server/tests/good_urls.txt
  servers/scrapping-server/tests/test_scrapers.py
Labels: enhancement, new feature, python, scraping-server
