Repository kanha638/Price-Tracker, pull requests merged in 2023-08, with the labels that each got.

#108 Added Price Drop Mail on Notification server!
  servers/notification/src/controller/product.controller.ts
  servers/notification/src/index.ts
  servers/notification/src/mailers/product.ts
  servers/notification/src/routes/product.ts
  servers/notification/src/templates/product.ts
Labels: enhancement, new feature, notification-server

#120 added notification page ui
  client/src/components/header/Search.jsx
  client/src/pages/Home.jsx
  client/src/pages/Notification.jsx
Labels: enhancement

#109 Added Product Page
  client/src/assets/images/graph2.png
  client/src/components/carousel/CorouselCard.jsx
  client/src/components/header/Search.jsx
  client/src/components/shops/ShopBox.jsx
  client/src/middleware/notification.js
  client/src/middleware/product.js
  client/src/middleware/user.js
  client/src/pages/Home.jsx
  client/src/pages/Notification.jsx
  client/src/pages/Product.jsx
  client/src/slices/userSlice.js
  client/src/styles/style.css
  servers/public-server/src/controllers/files.controller.ts
  servers/public-server/src/controllers/product.controller.ts
  servers/public-server/src/routes/files.ts
Labels: enhancement, new feature, UI/UX

#122 added product page and notification
  client/src/assets/dummyData.js
  client/src/components/headSlider/HeadSliderCard.jsx
  client/src/components/headSlider/HeaderBox.jsx
  client/src/middleware/product.js
  client/src/pages/Notification.jsx
  client/src/pages/Product.jsx
  servers/public-server/prisma/schema.prisma
  servers/public-server/src/controllers/notification.controller.ts
Labels: enhancement
